version: "3"

networks:
  frontend:
    external: true

services:
  nginx: 
    image: "nginx:alpine"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-conf:/etc/nginx
      - nginx-webroot:/usr/share/nginx/html
      - certbot-certs:/var/lib/letsencrypt
      - certbot-conf:/etc/letsencrypt
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - frontend
      - default

volumes:
  nginx-conf: 
  nginx-webroot:
  certbot-conf:
  certbot-certs:
